spring:
  application:
    name: demo

  datasource:
    url: 'jdbc:mariadb://192.168.80.23:3306/practice'
    driver-class-name: org.mariadb.jdbc.Driver
    username: yjs
    password: qwer1234

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace